#!/usr/bin/env bash

# Source our templates
# shellcheck disable=SC1091
. .templates.sh

## Filenames and paths
SCRP_NME="$(basename "${0}")"
JRNL_PTH="journal/"
WORK_DIR="work/"

## Card titles
JRNL_TTL="$(date +%y-%m-%d)"
ZETL_TTL=$(date +"%Y%m%d%H%M")

_print_help() {
  cat <<HEREDOC
Helper script to generate a zettelkasten card
Usage:
  ${SCRP_NME} [<arguments>]

Options:
  -h | --help     Show this screen.
  -d | --daily    Daily tasks in Journal/YYYY/MMM
  -j | --journal  Journal card  in Journal/YYYY/MMM
  -w | --work     work created under Work
  -n | --new      general card created in main zet dir
  -c | --clean    formats all *.md files using prettier
HEREDOC
}

_clean_title() {
  echo "$*" | sed 's/ /_/g' | tr '[:upper:]' '[:lower:]'
}
_populate_card() {
  echo -e "$META_STR\n$TEMPLATE" >"$1"
}

_edit_card() {
  vi "+normal G$" +startinsert! "$1"
}
_prettify_card() {
  npx prettier --write "$1"
}

_populate_edit_prettify_card() {
  local _CARD="$1"
  _populate_card "$_CARD"
  _edit_card "$_CARD"
  _prettify_card "$_CARD"
}

_prettify_all() {
  npx prettier --write ./**/*.md
}

_fix_filename() {
  for file in {**,.}/*.md; do
    mv -n "$file" "$(_clean_title "$file")"
  done
}

# Clean zettel
# - prettifies files
# lowercases, and removes spaces from filenames
_cz() {
  _prettify_all
  _fix_filename
}

# a '#' followed by a letter, number or em-dash
# should be consifered a tag.
# convert to lower case, ignore duplicates
_hashed_tags() {
  grep -roh "#\w[a-Z0-9\-]*" ./*.md | tr '[:upper:]' '[:lower:]' | sort -u
}

# badly formatted markdown table; prettier will clean this.
_make_table() {
  tags=$(_hashed_tags)
  printf "| tag \t| count|\n|:---|:---|\n"
  for tag in $tags; do
    count=$(grep -ir "$tag" ./*.md | wc -l)
    printf "%s| $tag \t| $count |\n "
  done
}

_network_tags() {
  ## for future use - filename & title for each tag
  tags=$(_hashed_tags)
  for tag in $tags; do
    for match in $(grep -irl "$tag" ./*.md); do
      title=$(grep "^# [a-Z0-9]*" "$match" | head -1)
      printf "%s$tag, $match, $title \n"
    done
  done
}

###### OPTION PARSING ##########################################

OPTIONS=chdjwnt
LONGOPTS=clean,tags,help,daily,journal,work,new
! PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTS --name "$0" -- "$@")

if [[ ${PIPESTATUS[0]} -ne 0 ]]; then
  # e.g. return value is 1
  #  then getopt has complained about wrong arguments to stdout
  exit 2
fi
# read getopt’s output this way to handle the quoting right:
eval set -- "$PARSED"

if [ "$1" == '--' ]; then
  ## no options passed = help message
  _print_help
else
  while true; do
    case "$1" in
    -d | --daily)
      TAGS="Daily"
      TITLE="$JRNL_TTL - DAILY"
      TEMPLATE=$(daily_template)
      META_STR="$(meta)"
      CARD="$JRNL_PTH/$JRNL_TTL.daily.md"
      shift
      ;;
    -j | --journal)
      TAGS="journal"
      TITLE=$JRNL_TTL
      TEMPLATE=$(journal_template)
      META_STR="$(meta)"
      CARD="$JRNL_PTH$TITLE.md"
      _populate_edit_prettify_card "$CARD"
      shift
      ;;
    -w | --work)
      shift
      TAGS="work"
      title="$*"
      TITLE=${title#??}
      CARD="$WORK_DIR$ZETL_TTL-$(_clean_title "$TITLE").md"
      TEMPLATE=$(new_template)
      META_STR="$(meta)"
      _populate_edit_prettify_card "$CARD"
      ;;
    -c | --clean)
      _cz
      shift
      ;;
    -n | --new)
      shift
      title="$*"
      TITLE=${title#??}
      CARD="$ZETL_TTL-$(_clean_title "$TITLE").md"
      TEMPLATE=$(new_template)
      META_STR="$(meta)"
      _populate_edit_prettify_card "$CARD"
      ;;
    -t | --tags)
      shift
      TAGS="tags"
      TITLE="TAGS"
      CARD="$TITLE.markdown"
      TEMPLATE="$(tags_template)"
      META_STR="$(meta)"
      _populate_card $CARD
      _prettify_card $CARD
      ;;
    -h | --help)
      _print_help
      shift
      ;;
    --)
      shift
      break
      ;;
    *)
      _print_help
      ;;
    esac
  done
fi
